version: '3.4'

services:
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile   
  
  orderdb:
    image: mcr.microsoft.com/mssql/server
    